[2024-12-17T16:10:20.522+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.сreate_tables manual__2024-12-17T16:10:19.829824+00:00 [queued]>
[2024-12-17T16:10:20.529+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.сreate_tables manual__2024-12-17T16:10:19.829824+00:00 [queued]>
[2024-12-17T16:10:20.530+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-12-17T16:10:20.546+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): сreate_tables> on 2024-12-17 16:10:19.829824+00:00
[2024-12-17T16:10:20.549+0000] {standard_task_runner.py:57} INFO - Started process 3658 to run task
[2024-12-17T16:10:20.554+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'сreate_tables', 'manual__2024-12-17T16:10:19.829824+00:00', '--job-id', '158', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp1dv9_xcm']
[2024-12-17T16:10:20.556+0000] {standard_task_runner.py:85} INFO - Job 158: Subtask сreate_tables
[2024-12-17T16:10:20.576+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-17T16:10:20.613+0000] {task_command.py:415} INFO - Running <TaskInstance: main_dag.сreate_tables manual__2024-12-17T16:10:19.829824+00:00 [running]> on host 00b941a4a1a3
[2024-12-17T16:10:20.701+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='сreate_tables' AIRFLOW_CTX_EXECUTION_DATE='2024-12-17T16:10:19.829824+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-17T16:10:19.829824+00:00'
[2024-12-17T16:10:20.713+0000] {base.py:73} INFO - Using connection ID 'admin' for task execution.
[2024-12-17T16:10:20.758+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-12-17T16:10:20.771+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=сreate_tables, execution_date=20241217T161019, start_date=20241217T161020, end_date=20241217T161020
[2024-12-17T16:10:20.806+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-12-17T16:10:20.823+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
